#!/usr/bin/env node
/**
 * Regenerate llms-full.txt from the real documentation set, so the AI-facing
 * mirror can never drift from what humans read. Run after any docs change:
 *
 *   node scripts/build-llms.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs'
import { join, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')

const SOURCES = [
  'README.md',
  'docs/getting-started.md',
  'docs/configuration.md',
  'docs/alerts.md',
  'docs/commands.md',
  'docs/cli.md',
  'docs/self-hosting.md',
  'docs/architecture.md',
  'docs/troubleshooting.md',
  'tutorials/01-your-own-bot.md',
  'tutorials/02-watch-a-wallet.md',
  'tutorials/03-public-channel.md',
  'AGENTS.md',
]

const header = `# robinhood-volume-alerts, complete documentation
# Generated by scripts/build-llms.mjs from the files named below. Do not edit by hand.
# Repository: https://github.com/nirholas/robinhood-volume-alerts
# Package:    https://www.npmjs.com/package/robinhood-volume-alerts
`

const parts = [header]
for (const rel of SOURCES) {
  const body = readFileSync(join(root, rel), 'utf8').trim()
  parts.push(`\n\n<!-- ============ ${rel} ============ -->\n\n${body}`)
}

writeFileSync(join(root, 'llms-full.txt'), `${parts.join('')}\n`)
console.log(`llms-full.txt built from ${SOURCES.length} sources`)
